import { fontFiraCode } from "@/fonts";
import { Metadata } from "next";
import { PiCardsFill } from "react-icons/pi";

type PropsLayout = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsLayout) {
  return (
    <main className="w-full h-auto flex-1 flex flex-col bg-white dark:bg-neutral-950 ">
      <header className="p-2 bg-zinc-50 border-b dark:border-zinc-800 dark:bg-zinc-900 z-30">
        <div className="flex justify-between mx-auto max-w-main items-center dark:text-zinc-300">
          <div className="flex text-zinc-100 bg-indigo-600 p-1 px-2 rounded items-center gap-2">
            <PiCardsFill className="text-white" />
            <h1 className={`${fontFiraCode} text-md`}>Flards</h1>
          </div>
          <div className="flex text-zinc-500 dark:text-zinc-200">
            <button
              className={`${fontFiraCode} border bg-white text-zinc-800 rounded text-sm hover:shadow-lg dark:bg-zinc-700 dark:text-white transition-all p-1 px-3 dark:border-zinc-700 opacity-90 hover:opacity-100 capitalize`}
            >
              Create account
            </button>
          </div>
        </div>
      </header>

      <section className="flex flex-1 w-[95%] mx-auto relative">{children}</section>
      <div className="fixed top-0 left-0 w-full h-screen overflow-hidden">
        <div className="grid-image"></div>
      </div>
    </main>
  );
}
