import { fontSaira } from "@/fonts";
import { Metadata } from "next";

type PropsLayout = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Entrar",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsLayout) {
  return (
    <main className="w-full h-auto flex-1 flex flex-col bg-gradient-radial from-gray-50 to-white dark:bg-gradient-to-b dark:from-neutral-900 dark:to-neutral-950 ">
      <header className="p-2 bg-transparent z-30">
        <div className="flex justify-between mx-auto max-w-main items-center dark:text-zinc-300">
          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-2">
              <h1 className={`${fontSaira} text-2xl text-indigo-500 font-semibold`}>Organizze</h1>
            </div>
          </div>
          <div className="flex text-zinc-500 dark:text-zinc-200">
            <button
              className={`${fontSaira} bg-indigo-600 text-white rounded hover:shadow-lg dark:text-white transition-all p-2 px-3 opacity-90 hover:opacity-100 capitalize`}
            >
              Criar nova conta!
            </button>
          </div>
        </div>
      </header>

      <section className="flex flex-1 w-[95%] mx-auto relative">
        {children}
      </section>
      <div className="fixed top-0 left-0 w-full h-screen overflow-hidden">
        <div className="grid-image"></div>
      </div>
    </main>
  );
}
