import { fontSaira } from "@/fonts";
import { Metadata } from "next";
import { SiSendgrid } from "react-icons/si";
import { ToastContainer } from "react-toastify";

type PropsLayout = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Entrar",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsLayout) {
  return (
    <main
      className={`w-full h-auto flex-1 flex flex-col bg-gradient-radial from-gray-50 to-white dark:bg-gradient-to-b dark:from-neutral-900 dark:to-neutral-950 `}
    >
      <ToastContainer theme="dark" hideProgressBar autoClose={1000}/>
      <header className="p-2 flex flex-col items-center mt-10 bg-transparent z-30">
        <div className="w-14 h-14 bg-gray-800 rounded-lg border-2 border-indigo-500/50 shadow-xl grid place-items-center text-indigo-300 shadow-indigo-300 dark:shadow-indigo-500/50">
          <SiSendgrid />
        </div>

        <div className="text-3xl mt-5 text-gray-700 font-semibold dark:text-gray-200">
          <span className={fontSaira}>Login</span>
        </div>
      </header>

      <section className="flex w-[95%] mt-5 mx-auto relative">
        {children}
      </section>

      <div className="fixed top-0 left-0 w-full h-screen overflow-hidden">
        <div className="grid-image"></div>
      </div>
    </main>
  );
}
