@HOST = http://localhost:9000

POST {{HOST}}/users HTTP/1.1
Content-Type: application/json

{
  "firstName": "TESTES",
  "lastName": "TESTES",
  "email": "example3@gmail.com",
  "password": "example3"
}
### 

GET {{HOST}}/users/mine HTTP/1.1
Content-Type: application/json
###

# @name auth

POST {{HOST}}/auth HTTP/1.1
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "example"
}
###

# @name workspaces

POST {{HOST}}/workspaces HTTP/1.1
Content-Type: application/json

{
  "name": "my workspace 4",
  "parentId": "cceef1b4-9b09-40df-9975-ae2385317d20"
}
###

GET {{HOST}}/workspaces HTTP/1.1
###
GET {{HOST}}/workspaces/tree HTTP/1.1
###
GET {{HOST}}/workspaces/tree/577bc00a-c9eb-4f2e-a416-cc83e8d91608 HTTP/1.1
###
GET {{HOST}}/workspaces/FleaLUR1w0eh HTTP/1.1
###
DELETE {{HOST}}/workspaces/g0lK39IY1fEd HTTP/1.1
###

# @name cards
POST {{HOST}}/cards HTTP/1.1
Content-Type: application/json

{
  "title": "init project",
  "content": "<p>example content!</p>",
  "workspaceId": "577bc00a-c9eb-4f2e-a416-cc83e8d91608"
}
###
PUT {{HOST}}/cards/99G4tPfFYaXe HTTP/1.1
Content-Type: application/json

{
  "title": "this is example",
  "content": "<p>Test</p>"
}
###
GET {{HOST}}/cards/99G4tPfFYaXe HTTP/1.1
Content-Type: application/json
