import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Organizze",
  description: "Generated by create next app",
};

export default async function Layout({ children }: LayoutProps) {
  const cookiesStore = cookies();
  const accessToken = cookiesStore.get("__access_token")?.value;
  const refreshToken = cookiesStore.get("__refresh_token")?.value;

  if (!accessToken) {
    redirect("/");
  }

  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/users/mine`,
      {
        cache: "no-store",
        headers: {
          Cookie: `__access_token=${accessToken};__refresh_token=${refreshToken}`,
        },
      }
    );

    if (res.ok) {
      const responseJSON = await res.json();
      if (responseJSON.firstName) {
        return children;
      }
    }

    throw new Error("Sessão inválida ou expirada.");
  } catch (error) {
    console.log(error);
    redirect("/login");
  }
}
