import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Flards",
  description: "Generated by create next app",
};

export default async function Layout({ children }: LayoutProps) {
  const cookiesStore = cookies();

  const accessToken = cookiesStore.get("__access_token")?.value;
  const refreshToken = cookiesStore.get("__refresh_token")?.value;

  try {
    const res = await fetch("http://localhost:9000/users/mine", {
      credentials: "include",
      headers: {
        Cookie: `__access_token=${accessToken}; __refresh_token=${refreshToken}`,
      },
    });

    const responseJSON = await res.json();

    if (responseJSON.firstName) {
      return children;
    }

    throw new Error();
  } catch (error) {
    redirect("/");
  }
}
